from vm import *
import sys
import argparse

vm = VM()
vm.initVm()

def repl():
	print("> ", end='', flush=True)
	for line in sys.stdin:
		vm.interpret(line)
		print("> ", end='', flush=True)

def readFile(path):
	try:
		f = open(path, "r")
		all_lines = f.readlines()
		buffer = ""
		for line in all_lines:
			buffer += line
		f.close()
		return buffer
	except IOError as e:
		print("Could not open file: {}".format(path), file=sys.stderr)
		exit(74)

def runFile(path):
	source = readFile(path)
	result = vm.interpret(source)
	if (result == InterpretResult.INTERPRET_COMPILE_ERROR):
		return(65)
	if (result == InterpretResult.INTERPRET_RUNTIME_ERROR):
		return(70)

parser = argparse.ArgumentParser(description='Run lox compiler and VM.')
parser.add_argument('filename')
parser.add_argument('--debug-print-code', help='Print instructions generated by compiler', action='store_true')
args = parser.parse_args()

if args.debug_print_code == True:
	Compiler.DEBUG_PRINT_CODE = 1

if args.filename == '-':
	repl()
else:
	runFile(args.filename)

exit(0)

